### ISSUE TITLE
Terminal stuck after generation

### ISSUE THREAD

**Issue by mariobrosch** [queenvictoria/ember-cli-openapi-generate#6]
When I run the addon via command in terminal, the terminal freezes after generating all the models. When I comment out the return deffered.promise; line, it works without freezing, but the models arent generated.

**Comment by queenvictoria** [comment]
I've not come across that. Can I see your openapi.json?

**Comment by mariobrosch** [comment]
i use this for parsing:
http://petstore.swagger.io/v2/swagger.json

**Comment by mariobrosch** [comment]
the models are created perfectly :(. But the terminal stops. Seems like there is a process waiting for something.

**Comment by mariobrosch** [comment]
Hi @queenvictoria ,

Forked my own version, but that one locally is a mess right now :(.

Got back to my local installation and found out was was going on:
At some point the addon is saving the models. When I run it for now i ran into the problem that a file allready exists, but i manually changed some attributes. The terminal is waiting for an answer for overwrite or skip, but I didnt see the question in the terminal and came by after accidentially pushing the Y button on my keyboard.

Next step I ran into a similar problem, when all files are identical, the process isnt stopped properly leaving the terminal in a kind of frozen state.

Do you have a solution?

**Comment by queenvictoria** [comment]
So the scenario is
* The models already exist
* There are no changes

And the outcome is
* The command never exits.

Is this correct?

**Comment by mariobrosch** [comment]
Yes!

**Comment by queenvictoria** [comment]
I've diagnosed this. What is happening is that `Blueprint.install` is detecting a change in the model and prompting for the user to approve the overwrite. The promises swallow these so nothing appears on screen. If you press `return` instead of `CTRL+C` then you 'yes' the prompts and the changes are applied. Neither CLI nor Blueprint seem to provide options for automatically overwriting. So at this time I have no fix.

The alternative is to use the `--cli` switch which will print out the ember commands which can then be copy pasted into the terminal.
